### ISSUE TITLE
For the attribute power_entity_id, the select domain is not accepted

### ISSUE THREAD

**Issue by lindsand** [jmcollin78/solar_optimizer#67]
First thanks for a great application!

This is related to #2 and similar in nature.

The BMW / Mini integration uses a selection list to set the charging current in steps of 1 A
https://www.home-assistant.io/integrations/bmw_connected_drive#selects

If I  put this in my configuration:

 power_entity_id: "select.x1_xdrive25e_ac_charging_limit"

then I get an error:

Invalid config for 'solar_optimizer' at solar_optimizer.yaml, line 22: 
Entity select.x1_xdrive25e_ac_charging_limit belongs to domain select, 
expected ['input_number', 'number'] for dictionary value 'solar_optimizer->devices->0->power_entity_id', 
got 'select.x1_xdrive25e_ac_charging_limit'

I changed **___init__.py_** for my installation a bit to test:
...

from homeassistant.components.number import DOMAIN as NUMBER_DOMAIN
from homeassistant.components.button import DOMAIN as BUTTON_DOMAIN
from homeassistant.components.light import DOMAIN as LIGHT_DOMAIN
**_from homeassistant.components.select import DOMAIN as SELECT_DOMAIN_**

...
                            vol.Optional("power_entity_id"): selector.EntitySelector(
                                selector.EntitySelectorConfig(
                                    domain=[INPUT_NUMBER_DOMAIN, NUMBER_DOMAIN, **_SELECT_DOMAIN_**]

After that the selection list is accepted and I can use **_service call select.select_option_** to set the value directly:
     ...the power change is done by a service call
     **change_power_service: "select/select_option"**

I'm using a input_number helper and automation for the moment to set the value but it's difficult to keep the values in sync as they can be changed by multiple applications. So it would be clearer and more stable to have a direct setup.

...
action: select.select_option
target:
  entity_id: select.x1_xdrive25e_ac_charging_limit
data:
  option: "{{ int(states('input_number.x1_xdrive25e_ac_charging_limit')) }}"

**Comment by jmcollin78** [comment]
Hello, fine ! I will integrate this into the next release.

If you are able to do a PR, then I can merge it immediatly.

**Comment by lindsand** [comment]
Next release is fine. I'm not in a hurry, I live in the north  and the sun starts to be lazy already this time of the year.
So I'm preparing for next spring...

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/solar_optimizer/releases/tag/3.1.0

**Comment by lindsand** [comment]
I'm not authorized to reopen issues so I just added the comment above.

**Comment by jmcollin78** [comment]
Hello,
I understoodd it was for the activation / deactivation entity. I don't read carefully.
This cannot work with a select for the power_entity_id. A power_entity need to be an integer or a number. SO calculate the value with power / divide_power (W / Volt) -> A. So I need a number here and map a number to a select is not easy in a general way.

So what you have to do, is to create a input_number, listen to the change to this input_number and change your select accordlingly.

**Comment by lindsand** [comment]
My entity for the charging current  "select.x1_xdrive25e_ac_charging_limit" is an integer with possible values 6, 7, 8, 9, .. [A]

I'm currently testing with limits power_max': 1840, 'power_min': 1380, 'power_step': 230 giving possible values 8, 7 or 6 for the current. SO apparently calculates the new value for the current but fails when calling the select/select_option.
- I have tested by passing integers (6, 7, 8) to the select/select_option and that works.

Could it be that SO is passing '9 A' with unit A included and not a simple integer  '9' ?
- by the way, **2070 / 230 = 9** is outside the limits [1380, 1840] so that should be cut to 8.

2025-03-27 14:30:16.053 DEBUG (MainThread) [custom_components.solar_optimizer.simulated_annealing_algo] Adding -230 power to current_power (1840)
2025-03-27 14:30:16.053 DEBUG (MainThread) [custom_components.solar_optimizer.simulated_annealing_algo] New requested_power is 1610
2025-03-27 14:30:16.053 DEBUG (MainThread) [custom_components.solar_optimizer.simulated_annealing_algo] Adding -230 power to current_power (1840)
2025-03-27 14:30:16.053 DEBUG (MainThread) [custom_components.solar_optimizer.simulated_annealing_algo] New requested_power is 1610
2025-03-27 14:30:16.053 DEBUG (MainThread) [custom_components.solar_optimizer.coordinator] Dealing with best_solution for X1 Charger - {'power_max': 1840, 'power_min': 1380, 'power_step': 230, 'current_power': 5520, 'requested_power': 2070, 'name': 'X1 Charger', 'state': True, 'is_usable': True, 'is_waiting': True, 'can_change_power': True}
2025-03-27 14:30:16.054 DEBUG (MainThread) [custom_components.solar_optimizer.managed_device] X1 Charger is active
2025-03-27 14:30:16.054 DEBUG (MainThread) [custom_components.solar_optimizer.coordinator] Change power of X1 Charger to 2070
2025-03-27 14:30:16.054 DEBUG (MainThread) [custom_components.solar_optimizer.managed_device] Applying action ChangePower for entity switch.pro1pm_switch_0. **requested_power=2070**
2025-03-27 14:30:16.054 DEBUG (MainThread) [custom_components.solar_optimizer.managed_device] Next availability date for power change for X1 Charger is 2025-03-27 14:35:16.054799+02:00
2025-03-27 14:30:16.054 INFO (MainThread) [custom_components.solar_optimizer.managed_device] **Calling service select/select_option for entity select.x1_xdrive25e_ac_charging_limit**
2025-03-27 14:30:16.060 ERROR (MainThread) [custom_components.solar_optimizer.managed_device] **extra keys not allowed @ data['value']**
Traceback (most recent call last):
  File "/config/custom_components/solar_optimizer/managed_device.py", line 65, in do_service_action
    await hass.services.async_call(
        domain, action, service_data=service_data, target=target
    )
  File "/usr/src/homeassistant/homeassistant/core.py", line 2759, in async_call
    processed_data: dict[str, Any] = handler.schema(service_data)
                                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 259, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 386, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 382, in _exec
    v = func(v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 382, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.**MultipleInvalid: extra keys not allowed @ data['value'**]
2025-03-27 14:30:16.066 INFO (MainThread) [custom_components.solar_optimizer.managed_device] Sending event solar_optimizer_state_change_event with action ChangePower for entity select.x1_xdrive25e_ac_charging_limit with requested_power 2070 and current_power 5520
2025-03-27 14:30:16.067 INFO (MainThread) [custom_components.solar_optimizer.coordinator] Calculated data are: {'power_production': 1463, 'power_production_brut': 1343.0, 'power_consumption': 3224.0, 'sell_cost': 0.001, 'buy_cost': 0.077800935, 'sell_tax_percent': 0.0, 'battery_soc': 0, 'battery_charge_power': 0, 'best_solution': [{'power_max': 1840, 'power_min': 1380, 'power_step': 230, 'current_power': 5520, 'requested_power': 2070, 'name': 'X1 Charger', 'state': True, 'is_usable': True, 'is_waiting': True, 'can_change_power': True}], 'best_objective': 2.8679862745283415, 'total_power': 2070, 'x1_charger': <custom_components.solar_optimizer.managed_device.ManagedDevice object at 0x7f88adbd90>}
2025-03-27 14:30:16.067 DEBUG (MainThread) [custom_components.solar_optimizer.coordinator] Finished fetching Solar Optimizer data in 0.075 seconds (success: True)
2025-03-27 14:30:16.068 DEBUG (MainThread) [custom_components.solar_optimizer.switch] Calling _handle_coordinator_update for Active
2025-03-27 14:30:16.068 DEBUG (MainThread) [custom_components.solar_optimizer.switch] No device water_heater found ...
2025-03-27 14:30:16.068 DEBUG (MainThread) [custom_components.solar_optimizer.switch] Calling _handle_coordinator_update for Active
2025-03-27 14:30:16.068 DEBUG (MainThread) [custom_components.solar_optimizer.managed_device] X1 Charger is active

**Comment by jmcollin78** [comment]
Hello, sorry but once again it is not possible. Add an automation to integrate into your environment.
